### PR TITLE
Improves DMI saving (smaller files, better formatting)

### PR DESCRIPTION
**Pull request by LemonInTheDark**
## What I did 

[Actually compresses dmis when saving them](https://github.com/spacestation13/dmi-rust/commit/6307c1ad333f58da12a3f639d29d43f72a856b23)

We've been using the write_to wrapper function, which doesn't allow us to pass in a compression level.
This means we've been using the default, which is for some reason the fastest/worst for file size.

This commit instead "inlines" the write_to function, and uses the ~~Best~~ Average compression method (very good compression, acceptable speed)

This strategy reduces a large file I tested ([screen_cyborg.dmi](https://github.com/tgstation/tgstation/blob/492452a3ce9f8d571e07bbdce28874eb345de26a/icons/hud/screen_cyborg.dmi)) from 82kb to 23kb (byond's output if you're curious is about 26kb)

I've also added saving to the test suite, to ensure the path gets walked and to allow for visual inspection if changes are made

[Improves our image formatting somewhat](https://github.com/spacestation13/dmi-rust/commit/d5edae4fc3c3378422d2c508711cbb9e8a2804a5)

We, like byond, arrange our saved DMIs in squares. However unlike byond we currently don't remove extra height that we don't use, which leads to odd looking files. This commit fixes that

Of note, this isn't exactly the same as byond. Byond squares based off PIXEL count, whereas we square based off ICON count. Could look into fixing this if anyone cares but it's like eh yk?

## What I didn't do

I haven't converted us over to a less cursed image saving format. We don't really need much of what the image crate provides here, but I don't trust myself to deal with the like, requirements for sending empty data that the recommended solution, [lodepng](https://docs.rs/lodepng/latest/lodepng), would require.

I can look into it if you'd like I'm just not totally confident in my ability to do it performantly without some oversight.

### CODE REVIEW

**Comment by ZeWaka** [comment]
Do you think you could compare the relative speeds for a large DMI? Just want to make sure we're not paying a 100x increase or something (and if so, we could try and move it up a level). 

Honestly it should be a unit test.... :whelm:

**Comment by LemonInTheDark** [comment]
> Do you think you could compare the relative speeds for a large DMI? Just want to make sure we're not paying a 100x increase or something (and if so, we could try and move it up a level).
> 
> Honestly it should be a unit test.... :whelm:

Ran it on the biggest dmi I know of, [wallening's hierophant walls ](https://github.com/wall-nerds/wallening/blob/c13ba085918c6647b3294bf36dff83eb7123f1e4/icons/turf/walls/hierophant_wall.dmi)
All numbers come from the load_and_save test in release mode on my laptop

Fast strategy took 0.61s and produced 3.74mb
Best strategy took 1.31s and produced 992kb
Default strategy took 0.88s and produced 999kb
(There are other, deprecated strategies, but I'm just gonna leave em alone)

**Review by ZeWaka — APPROVED** [review]
Looks all good now.

**Comment by LemonInTheDark** [comment]
Pogged

**Comment by LemonInTheDark** [comment]
For the record:
It seems like default results in file sizes lower then standard dreammaker for most dmis. It is still way better then the fast option tho, it goes from like 500kb -> 99kb -> 9kb
Idk if that changes the calculus on the speed here but even if we just leave it at default this is a strong win.

**Pull request merged**
